### PR TITLE
fix npm audit issues

### PR DESCRIPTION
**Pull request by jimexist**
ran

```bash
npm audit fix
npm audit
```

### CODE REVIEW

**Comment by jimexist** [comment]
there's prototype pollution issue with lodash

**Review by ljharb — APPROVED** [review]
semver means this is automatic, unless you have a lockfile (which we discourage for packages)

**Comment by jimexist** [comment]
@ljharb that makes sense - but this probably (only) helps with this package development per-sey

**Comment by jimexist** [comment]
@ljharb i am sure that published files don't contain that lock?

**Comment by ljharb** [comment]
You’re correct - package-lock is a dev-only lockfile, so it only protects/affects developers, which is the reason it’s not a good idea on libraries :-)

**Comment by jimexist** [comment]
@ljharb do you know a way to disable that? i'd think that at least it'll help to make development environment more reproducible

**Comment by ljharb** [comment]
Yep! add `package-lock=false` to `.npmrc` and gitignore the 3 lockfile filenames.

**Pull request merged**
